## Import the numpy module

In [15]:
import numpy as np

## The basics numpy codes

In [3]:
a = np.array([1,2,3])

In [4]:
print(a)

[1 2 3]


In [8]:
a2 = np.array([1,2,3],dtype='float32')

In [9]:
print(a2)

[1. 2. 3.]


In [17]:
a3 = np.array([[1,2,3],[4,5,6]])
print(a3)

[[1 2 3]
 [4 5 6]]


In [10]:
np.array([range(i , i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Different types of arrays

In [18]:
# A length 10 integer array filled with zeros

np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
# a 3x5 floating array filled with ones

np.ones((3,5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
# a 4x7 array filed with 3.14

np.full((4,7), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14]])

In [23]:
# array filled with linear sequence, starting at 0, ending at 20 and stepping by 2

np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
# array of five values evenly spaced between 0 and 1

np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
# 3x3 array of uniformly distributed random values between 0 and 1

np.random.random((3,3))

array([[0.31535   , 0.86679258, 0.55487896],
       [0.09827913, 0.98191426, 0.07090431],
       [0.66534732, 0.94799526, 0.30371071]])

In [26]:
# 3x3 array of normal distributed random values with mean = 0 and SD = 1

np.random.normal(0,1,(3,3))

array([[-1.02307222, -0.4771296 ,  2.09677217],
       [ 2.5283414 , -0.8634912 , -1.68496334],
       [ 2.52917411,  0.27696616, -0.92935523]])

In [27]:
# 3x3 array of random integers within the interval 0,10

np.random.randint(0,10,(3,3))

array([[7, 1, 8],
       [5, 1, 8],
       [4, 1, 8]])

In [28]:
# 3x3 identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])