In [1]:
import numpy as np
np.random.seed(0)

In [2]:
x1 = np.random.randint(10, size = 6) # One diamensional array
x2 = np.random.randint(10, size = (3,4)) # Two diamensional array
x3 = np.random.randint(10, size = (3,4,5)) # Three diamensional array

In [3]:
x1

array([5, 0, 3, 3, 7, 9])

In [4]:
x1[0]

5

#### To index from the end of the array, you can use negative indices

In [5]:
x1[-1]

9

In [6]:
x1[-2]

7

#### In a multidimensioanl array, you access items using coma-seperated tuple of indices

In [7]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [8]:
x2[0,0]

3

In [9]:
x2[2,0]

1

In [10]:
x2[2,-1]

7

#### You can modify values using any of the above index notation

In [11]:
x2[0,0] = 12

In [12]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])