### Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the SLICE notation, marked by colon (:) character 

## x[start:stop:step]

In [1]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10, size = 6) # One diamensional array
x2 = np.random.randint(10, size = (3,4)) # Two diamensional array
x3 = np.random.randint(10, size = (3,4,5)) # Three diamensional array

In [2]:
x = np.arange(10)

In [3]:
x[:5] # first five elements

array([0, 1, 2, 3, 4])

In [4]:
x[5:] #element after index 5

array([5, 6, 7, 8, 9])

In [5]:
x[4:7] # middle subarray

array([4, 5, 6])

In [6]:
x[::2] #every other element

array([0, 2, 4, 6, 8])

In [7]:
x[1::2] # every other element starting at index 1

array([1, 3, 5, 7, 9])

In [8]:
x[::-1] # all elements reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [10]:
x[5::-1] # reversed every other element from index 5

array([5, 4, 3, 2, 1, 0])

### Multidiamensional Arrays

In [11]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [12]:
x2[:2,:3] # two rows and three columns

array([[3, 5, 2],
       [7, 6, 8]])

In [13]:
x2[:3,::2] # three rows and every other column

array([[3, 2],
       [7, 8],
       [1, 7]])

In [14]:
x2[::-1,::-1] # every elements reversed together

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])